// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4weMNJ-igzYFfPKjy4H74pxgDQKMCxEM',
    appId: '1:1032684701:web:7a5571a4c22ac3d5fec074',
    messagingSenderId: '1032684701',
    projectId: 'musa-9dd6f',
    authDomain: 'musa-9dd6f.firebaseapp.com',
    storageBucket: 'musa-9dd6f.firebasestorage.app',
    measurementId: 'G-YWL612RC9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgGtGgYdk-jxELBbhSFkZhF_UbO3MSAbI',
    appId: '1:1032684701:android:3ba6ae7978400262fec074',
    messagingSenderId: '1032684701',
    projectId: 'musa-9dd6f',
    storageBucket: 'musa-9dd6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOrGtOwMPav_VUSw1AjkH4l3RlOU0DUJo',
    appId: '1:1032684701:ios:f3466b91223b32e4fec074',
    messagingSenderId: '1032684701',
    projectId: 'musa-9dd6f',
    storageBucket: 'musa-9dd6f.firebasestorage.app',
    iosClientId: '1032684701-bfula7ki49911bhg8ol5dg03vnsascuj.apps.googleusercontent.com',
    iosBundleId: 'com.example.musa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOrGtOwMPav_VUSw1AjkH4l3RlOU0DUJo',
    appId: '1:1032684701:ios:f3466b91223b32e4fec074',
    messagingSenderId: '1032684701',
    projectId: 'musa-9dd6f',
    storageBucket: 'musa-9dd6f.firebasestorage.app',
    iosClientId: '1032684701-bfula7ki49911bhg8ol5dg03vnsascuj.apps.googleusercontent.com',
    iosBundleId: 'com.example.musa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4weMNJ-igzYFfPKjy4H74pxgDQKMCxEM',
    appId: '1:1032684701:web:260a65d812f4188cfec074',
    messagingSenderId: '1032684701',
    projectId: 'musa-9dd6f',
    authDomain: 'musa-9dd6f.firebaseapp.com',
    storageBucket: 'musa-9dd6f.firebasestorage.app',
    measurementId: 'G-P63MPNR5C5',
  );
}
